joshua-study/effective-java

02장/01_생성자 대신 정적 팩토리 메소드를 고려하라_이재훈.md
docs: #01_생성자_대신_정적_팩토리_메소드를_고려하라_이재훈
정적 팩토리 메서드의 장점 5가지와 단점 2가지에 대해 정리했어요. 🙃
=> docs: #01_생성자_대신_정적_팩토리_메소드를_고려하라_이재훈

02장/01_생성자 대신 정적 팩토리 메소드를 고려하라_김선만.md
=> docs: #1 생성자 대신 정적 팩터리 메서드를 고려하라.

02장/02_생성자에 매개변수가 많다면 빌더를 고려하라_김선만.md
=> [#2] ITEM02작성_김선만

02장/02_생성자에 매개변수가 많다면 빌더를 고려하라_지선학.md
Item02 생성자에 매개변수가 많다면 빌더를 고려하라 정리하였습니다.
=> docs : Item02 생성자에 매개변수가 많다면 빌더를 고려하라

02장/03_private 생성자나 열겨 타입으로 싱글턴임을 보증하라_지선학.md
03_private 생성자나 열겨 타입으로 싱글턴임을 보증하라 정리하였습니다.
=> docs : [#3] 03_private 생성자나 열겨 타입으로 싱글턴임을 보증하라

02장/02_생성자에 매개변수가 많다면 빌더를 고려하라_이재훈.md
=> [#2] 생성자에 매개변수가 많다면 빌더를 고려하라_이재훈

02장/05_자원을 직접 명시하지 말고 의존 객체 주입을 사용하라_지선학.md
아이템 5 자원을 직접 명시하지 말고 의존 객체 주입을 사용하라를 정리하였습니다.
=> [#5]item05 정리_지선학

02장/05_자원을 직접 명시하지 말고 의존 객체 주입을 사용하라_장병준.md
=> [#5] item05_장병준

02장/07_다 쓴 객체 참조를 해제하라_지선학.md
아이템07 다 쓴 객체 참조를 해제하라 내용을 정리하였습니다.
=> docs:[#7]item07 정리_지선학

02장/08_finalizer와 cleaner 사용을 피하라_장병준.md
=> [#8] item08_장병준

02장/09_try-finally보다는 try-with-resources를 사용하라_장병준.md
try-finally보다는 try-with-resources를 사용하라.
=> [#9] item09_장병준

02장/08_finalizer와 cleaner 사용을 피하라_지선학.md
아이템08_finalizer와 cleaner 사용을 피하라를 정리하였습니다.
=> docs : [#8]item08 정리_지선학

02장/09_try-finally보다는 try-with-resources를 사용하라_지선학.md
아이템09_try-finally보다는 try-with-resource를 사용하라를 정리하였습니다.
=> docs:[#9]item09 정리_지선학

03장/11_equals를 재정의하려거든 hashCode도 재정의하라_장병준.md
equals를 재정의하려거든 hashCode도 재정의하라.
=> [#11] item11_장병준

03장/11_equals를 재정의하려거든 hashCode도 재정의하라_지선학.md
item11 equals를 재정의하려거든 hashCode도 재정의하라를 정리하였습니다.
=> dosc:[#11]item11 정리_지선학

03장/12_toString을 항상 재정의하라_지선학.md
아이템 12. toString을 항상 재정의하라를 정리하였습니다.
=> docs:[#12]item12 정리_지선학

03장/13_clone 재정의는 주의해서 진행하라_지선학.md
[아이템 13_clone 재정의는 주의해서 진행하라]를 정리하였습니다.
=> docs:[#13]item13 정리_지선학

03장/14_Comparable을 구현할지 고려하라_지선학.md
docs:[#14]item14 Comparable을 구현할지 고려하라를 정리하였습니다.
=> docs:[#14]item14 Comparable을 구현할지 고려하라_지선학

04장/17_변경 가능성을 최소화하라_지선학.md
아이템 17 [변경 가능성을 최소화하라]를 정리하였습니다.
=> docs:[#17]item17 아이템 17 [변경 가능성을 최소화하라] 정리_지선학

04장/18_상속보다는 컴포지션을 사용하라_지선학.md
docs:[#18]item18 상속보다는 컴포지션을 사용하라 내용을 정리하였습니다.
=> docs:[#18]item18 상속보다는 컴포지션을 사용하라_지선학

04장/23_태그 달린 클래스보다는 클래스 계층구조를 활용하라_지선학.md
아이템23. 태그 달린 클래스보다는 클래스 계층구조를 활용하라를 정리하였습니다.
=> docs:Item23_태그 달린 클래스보다는 클래스 계층구조를 활용하라_지선학

04장/25_톱레벨 클래스는 한 파일에 하나만 담으라_지선학.md
아이템25 톱레벨 클래스는 한 파일에 하나만 담으라 내용 정리하였습니다.
=> [#25]item25 톱레벨 클래스는 한 파일에 하나만 담으라_지선학

04장/28_배열보다는 리스트를 사용하라_지선학.md
아이템 28 배열보다는 리스트를 사용하라를 정리하였습니다.
=> docs:[#28]item28_배열보다는 리스트를 사용하라_지선학

05장/30_이왕이면 제네릭 메서드로 만들라_지선학.md
아이템 30 이왕이면 제네릭 메서드로 만들라를 정리하였습니다.
=> docs:Item30_이왕이면 제네릭 메서드로 만들라_지선학
